# Generated by Django 6.0.2 on 2026-04-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspect',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
